[package]
name = "alphabot"
version = "0.1.0"
authors = ["Alpha Chen <alpha.chen@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
warp = "0.1"
